overwrite: true
schema: 'https://testdrive.kompletecare.com/graphql'
documents: 'gql/**/*.gql'
generates:
  types/graphql.d.ts:
    - typescript-graphql-files-modules
  types/types.ts:
    - typescript
    - typescript-operations
